server:
  port: 3001
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
     defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
# 这是默认转发规则,可以不用配置,自动配置
zuul:
  routes:
   item-service: /item-service/**
   user-service: /user-service/**
   order-service: /order-service/**
  retryable: true